language: node_js
sudo: false
node_js:
- '8'
services: 
- xvfb
script: npm run-script travistest
deploy:
  provider: npm
  email: gmer@hcuge.ch
  skip_cleanup: true
  api_key:
    secure: PhEn5OekEi5oL7yP24MznaAk1hPw3euwscH+MEhV1m/lq00a7Zi0kH4x3DlC8f0jaRL2O70BPKA6cyeHM2Vi3vOb8sx1E14lHf8tT4eJd/Nfkh34Rgcf/wNeo5e8qbnQ9WLa42BtsRUWjd+CiFTlyLNVHWWBxkwKGuxSO8GTUcbjQs2pBW1JjpGFB3Q/clIVIHXlsUANtJh46w1sGX2RfoOKuqQtOs/2Uo48ivzzpf7Zj+zV091syXhTYKEmWUm/0j7nOSrNzGZw9E9HH6XEk62r71E2PxjZjPnBjk51w8ZaasUwYc5ArJBc32OuygBUoUcWMGl0Gho2nkasQ2n4K6z8k7zujV4Ct8uYz6Mwaf+1m32rd38LgrYdNmMoz5XoyTABqJvvWR5y+GEJaaI8fRpxMqpKbmmSizhNLNMxIQQejQfn5kCB1hbmytd/QMDTHI+0Bal3I/Dw0zhztOwMacThCzAPpzoHXDKyoybCvaHJ/bfTetC1+zRBwyxV+Et9p8V1X6Jc7++2AouTdk2fEEDTooHimD1UQSt9Y4kmT2ru7hAwUD+TMiRufTfWJPxkw7Q5SgIaoUgsMOHW6NvLrFB820ArVgazAZJ3pE6CTdI8tKcm0pA555wV9r8Yb3K9c6ByWViV+fIBRo01g7nanfZBCAYOCvNwl2Xtb3kv5hQ=
  on:
    repo: x2js/x2js
    branch: master
